[server]
# Configuration for Streamlit Cloud deployment
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Automatically open browser (disable for cloud deployment)
gatherUsageStats = false

[theme]
# App theme
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
